name: consulta_cep
description: "Um app de consultas de CEP (Brasil)"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  google_fonts: ^6.3.1

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: true
  windows:
    generate: true
  linux:
    generate: true
  web:
    generate: true
    background_color: "#3F51B5"
    theme_color: "#3F51B5"
  adaptive_icon_background: "#3F51B5"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
